[build-system]
requires = ["setuptools>=45"]
build-backend = "setuptools.build_meta"

[project]
name = "aplos"
version = "0.0.2"
description = "Easy Research Level models"
dependencies = [
    "torch>=2.0",
    "numpy",
    "matplotlib<=3.9",
    "tqdm",
    "dearpygui"
]

[tool.setuptools.packages.find]
where = ["."]